name: realtime_audio
description: "Audio package for realtime APIs like OpenAI Realtime or HumeAI Voice."
version: 0.0.6
homepage: "https://github.com/volskaya/realtime_audio.flutter"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.0
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.realtime_audio
        pluginClass: RealtimeAudioPlugin
      ios:
        pluginClass: RealtimeAudioPlugin
